Dir.glob('lib/tasks/*.rake').sort.each do |file|
  load(file)
end

desc 'generate CMYK PDF file'
task pdf_cmyk: :pdf do
  cmyk_pdf = BOOK + '_cmyk.pdf'
  sh "gs -dBATCH -dNOPAUSE -dSAFER " \
     "-sDEVICE=pdfwrite " \
     "-sColorConversionStrategy=CMYK " \
     "-dProcessColorModel=/DeviceCMYK " \
     "-dCompatibilityLevel=1.4 " \
     "-sOutputFile=#{cmyk_pdf} " \
     "#{BOOK_PDF}"
end
